---
- name: Update APT cache (Debian/Ubuntu)
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: Update Homebrew cache (macOS)
  homebrew:
    update_homebrew: true
  when: ansible_os_family == "Darwin"
