---
- name: 'Setup Git Credential Manager (Ubuntu)'
  become: true
  block:
    - name: 'Install GCM'
      ansible.builtin.apt:
        deb: https://github.com/git-ecosystem/git-credential-manager/releases/download/{{ git.gcm.version }}/gcm-linux_amd64.{{ git.gcm.version }}.deb
    - name: 'Configure GCM'
      ansible.builtin.command: 'git-credential-manager configure'
  when:
   - ansible_facts['distribution'] == 'Ubuntu'
   - wsl_enabled == false
- name: 'Setup Git Credential Manager (osx)'
  community.general.homebrew_cask:
    name: 'git-credential-manager'
    state: 'latest'
  when:
    - ansible_facts['os_family'] == 'Darwin'
- name: 'Install diff-so-fancy'
  become: true
  get_url:
    url: 'https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy'
    dest: '/usr/local/bin/diff-so-fancy'
    mode: '0755'
  tags:
    - 'update_deps'
- name: 'Install github cli (OSX)'
  homebrew:
    name: 'github/gh/gh'
    update_homebrew: true
  when:
    - ansible_facts['os_family'] == 'Darwin'

