---
- name: "Clone dotfiles to {{ dotfiles_dir }}"
  git:
    repo: 'https://github.com/bob1983/dotfiles.git'
    dest: "{{ dotfiles_dir }}"
    update: 'no'
- name: 'Download dircolors configuration'
  get_url:
    url: 'https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark'
    dest: "{{ dotfiles_dir }}/dircolors"
    mode: '0755'
- name: 'Install rcm (Ubuntu)'
  block:
    - name: 'Add thoughtbot keyring'
      become: true
      apt_key:
        url: 'https://apt.thoughtbot.com/thoughtbot.gpg.key'
        state: 'present'
    - name: 'Add thoughtbot soucelist'
      become: true
      apt_repository:
        repo: 'deb https://apt.thoughtbot.com/debian/ stable main'
        state: 'present'
        filename: 'thoughtbot'
    - name: 'Install rcm'
      become: true
      apt:
        name: 'rcm'
        state: 'present'
        update_cache: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install rcm (OSX)'
  block:
    - homebrew_tap:
        name: 'thoughtbot/formulae'
    - homebrew:
        name: 'rcm'
        state: 'present'
        update_homebrew: true
  when:
    - ansible_facts['os_family'] == 'Darwin'
- name: 'Run rcup'
  shell: "RCRC={{ dotfiles_dir }}/rcrc rcup -f"



