---
- name: 'Install zsh (Ubuntu)'
  become: true
  apt:
    name: 'zsh'
    state: 'latest'
    update_cache: true
  tags:
    - 'update_deps'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install zsh (osx)'
  homebrew:
    name: 'zsh'
    update_homebrew: true
  tags:
    - 'update_deps'
  when:
    - ansible_facts['os_family'] == 'Darwin'
- name: 'Use zsh as a login shell'
  become: true
  user:
    name: 'bob'
    shell: '/bin/zsh'
# - name: 'Check .zplug dir'
#   stat:
#     path: "{{ home_dir }}/.zplug"
#   register: zplug_dir
# - name: 'Install zplug'
#   shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
#   when: not zplug_dir.stat.exists

