#!/usr/bin/env ruby

# Key definition is placed at https://github.com/k0kubun/xremap/blob/6e8e1f21285ecedfa7ac88d703ad80d25a2699dd/src/x11_constants.c#L16
window class_not: 'gnome-terminal-server' do
  # emacs-like bindings
  remap 'C-b', to: 'Left'
  remap 'C-f', to: 'Right'
  remap 'C-p', to: 'Up'
  remap 'C-n', to: 'Down'

  # To show search window
  remap 'M-f', to: 'Ctrl-f'

  remap 'C-a', to: 'Home'
  remap 'C-e', to: 'End'

  remap 'C-h', to: 'BackSpace'
  remap 'C-d', to: 'Delete'
  remap 'M-h', to: 'Ctrl-BackSpace'
  remap 'M-d', to: 'Ctrl-Delete'

  remap 'Alt-n', to: 'Ctrl-n'
  %w[a z x c v w t l].each do |key|
    remap "Alt-#{key}", to: "C-#{key}"
  end
end

window class_only: %w[google-chrome chromium-browser] do
  # remap 'Alt-Shift-bracketright', to: 'C-Tab'
  # remap 'Alt-Shift-bracketleft', to: 'C-Shift-Tab'

  # I remmapped keycode 49 to Alt_R but the above keybinding
  # didn't work so I remap this keybinding for now
  remap 'Alt-bracketright', to: 'C-Tab'
  remap 'Alt-bracketleft', to: 'C-Shift-Tab'
end

# TODO: It might beteer to be done on atom keymapping
window class_only: %w[atom] do
  # Go to anything
  remap 'Alt-p', to: 'C-p'
end
