live_config_reload = true

[font]

normal = { "family" = "MesloLGS NF", "style" = "Regular" }
bold = { "family" = "MesloLGS NF", "style" = "Bold" }
italic = { "family" = "MesloLGS NF", "style" = "Italic" }

[env]

TERM = "xterm-256color"
