---
- block:
    - name: Install common packages (Ubuntu)
      package:
        name: "{{ packages.common }}"
        state: present
      become: yes

    - name: Install Linux-specific packages
      package:
        name: "{{ packages.linux }}"
        state: present
      become: yes
  when: ansible_os_family != "Darwin"

- block:
    - name: Install common packages (macOS)
      homebrew:
        name: "{{ packages.common }}"
        state: present

    - name: Install macOS-specific packages
      homebrew:
        name: "{{ packages.osx }}"
        state: present
  when: ansible_os_family == "Darwin"
