---
- name: 'Setup go (Ubuntu)'
  block:
    - name: 'Add go repository'
      become: true
      apt_repository:
        repo: 'ppa:longsleep/golang-backports'
    - name: 'Install go'
      become: true
      apt:
        name: 'golang-go'
        update_cache: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install ghq (Ubuntu)'
  shell: 'go install github.com/x-motemen/ghq@latest'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install ghq (osx)'
  homebrew:
    name: 'ghq'
  when:
    - ansible_facts['os_family'] == 'Darwin'
