---
- name: 'Install fonts (Ubuntu)'
  block:
    - name: "Ensure {{ home_dir }}/.fonts dir exists"
      file:
        path: "{{ home_dir }}/.fonts"
        state: 'directory'
    - name: 'Install fonts'
      get_url:
        url: "{{ item }}"
        dest: "{{ home_dir }}/.fonts/"
      loop:
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Italic.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold%20Italic.ttf'
      register: install_font_result
    - name: 'Update font cache'
      shell: 'fc-cache -fv'
      when:
        - install_font_result.changed
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install fonts (osx)'
  block:
    - name: 'Add cask-font'
      homebrew_tap:
        name: 'homebrew/cask-fonts'
    - name: 'Install nerdfont'
      homebrew_cask:
        name: 'font-hack-nerd-font'
  when:
    - ansible_facts['os_family'] == 'Darwin'
