---
- name: Install Nix package manager on Ubuntu
  become: yes

  block:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
        state: present
        update_cache: yes

    - name: Run Nix install script
      become: no
      shell: |
        curl -L https://nixos.org/nix/install | sh
      args:
        creates: /home/{{ ansible_user_id }}/.nix-profile
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

