---
- name: 'Install ripgrep (Ubuntu)'
  become: true
  apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/{{ rg_version }}/ripgrep_{{ rg_version }}_amd64.deb"
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install ripgrep (osx)'
  homebrew:
    name: 'ripgrep'
    update_homebrew: true
    state: 'latest'
  when:
    - ansible_facts['os_family'] == 'Darwin'
