---
- name: 'Install Volta'
  block:
    - name: 'Download and install Volta'
      shell: |
        curl https://get.volta.sh | bash
      args:
        creates: "{{ home_dir }}/.volta"

    - name: 'Install Node.js LTS via Volta'
      shell: "{{ home_dir }}/.volta/bin/volta install node@lts"
      args:
        creates: "{{ home_dir }}/.volta/tools/inventory/node"

    - name: 'Install npm latest via Volta (compatibility)'
      shell: "{{ home_dir }}/.volta/bin/volta install npm"

    - name: 'Install pnpm as main package manager via Volta'
      shell: "{{ home_dir }}/.volta/bin/volta install pnpm"
      args:
        creates: "{{ home_dir }}/.volta/tools/inventory/pnpm"

    - name: 'Configure pnpm store directory'
      shell: "{{ home_dir }}/.volta/bin/pnpm config set store-dir {{ home_dir }}/.pnpm-store"

    - name: 'Install yarn via Volta (optional)'
      shell: "{{ home_dir }}/.volta/bin/volta install yarn"
      ignore_errors: true

- name: 'Install common global packages via pnpm'
  shell: "{{ home_dir }}/.volta/bin/pnpm add -g {{ item }}"
  loop: "{{ volta_pnpm_global_packages }}"
  ignore_errors: true

- name: 'Install legacy packages via npm (if needed)'
  shell: "{{ home_dir }}/.volta/bin/npm install -g {{ item }}"
  loop: "{{ volta_npm_global_packages }}"
  ignore_errors: true
