---
- name: 'Gather package facts'
  package_facts:
    manager: 'apt'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
- name: 'Install slack'
  become: true
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
    - '"slack" not in ansible_facts.packages'

