---
- name: 'Install neovim'
  block:
    - name: 'Install dependencies'
      become: true
      apt:
        name: "{{ neovim_dependencies_ubuntu }}"
      vars:
        neovim_dependencies_ubuntu:
          - 'python-dev'
          - 'python-pip'
          - 'python3-dev'
          - 'python3-pip'
    - name: 'Add neovim repo'
      become: true
      apt_repository:
        repo: 'ppa:neovim-ppa/stable'
    - name: 'Install neovim'
      become: true
      apt:
        name: neovim
    - name: 'Configure python related'
      shell: "{{ item }} install --upgrade neovim"
      loop:
        - "{{ home_dir }}/.pyenv/shims/pip3"
        - pip2
    - name: 'Update editor path'
      become: true
      shell: "update-alternatives --set {{ item }}"
      loop:
        - editor $(which nvim)
        - vi $(which nvim)
        - vim $(which nvim)
    - name: 'Install plug.vim'
      shell:
        cmd: |
          curl -fLo {{ home_dir }}/.local/share/nvim/site/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      tags:
        - 'update_deps'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
  tags:
    - 'update_deps'
