Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'qpkorr/vim-bufkill'
Plug 'editorconfig/editorconfig-vim'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'tomasr/molokai'
Plug 'godlygeek/tabular'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tmux-plugins/vim-tmux'
Plug 'jlanzarotta/bufexplorer'
