---
- name: "Install xremap (Ubuntu)"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/xremap/xremap/releases/download/{{ xremap_version }}/xremap-linux-x86_64-{{ desktop_environment }}.zip"
    dest: "/usr/local/bin"
    mode: "0755"
    remote_src: true
