" Install vim plug automatically
if empty(glob('~/.vim/autoload'))
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')

source ~/.vim/plugins.vim

call plug#end()

syntax enable

source ~/.vim/base_config.vim
source ~/.vim/theme.vim
source ~/.vim/airline.vim
source ~/.vim/keybindings.vim
source ~/.vim/buffer.vim
source ~/.vim/netrw.vim
source ~/.vim/ag.vim
source ~/.vim/vimdiff.vim
source ~/.vim/fzf.vim
source ~/.vim/coc.vim

" Config for each languages
source ~/.vim/javascript.vim
source ~/.vim/markdown.vim
