# load zplug configuration
[[ -f $HOME/.zsh/zplug.zsh ]] && source $HOME/.zsh/zplug.zsh

# Load ubuntu related configurations

uname -v | grep -q "Ubuntu"
ubuntu=$?

if [ ${ubuntu} = 0 ]; then
  for zsh_source in $HOME/.zsh/configs/ubuntu/*.zsh; do
    source $zsh_source
  done
fi

# Load wsl(ubuntu) related configuration
uname -v | grep -q "Microsoft"
wsl=$?

if [ ${wsl} = 0 ]; then
  for zsh_source in $HOME/.zsh/configs/wsl/*.zsh; do
    source $zsh_source
  done

  # Set umask 022 only if it's wsl
  umask 022
fi

# Load osx related configurations

if [ "$(uname)" = 'Darwin' ]; then
  for zsh_source in $HOME/.zsh/configs/darwin/*.zsh; do
    source $zsh_source
  done
fi

# load custom configurations
for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

# load fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[[ -f $HOME/.aliases ]] && source $HOME/.aliases

# load functions
for zsh_source in $HOME/.zsh/functions/*.zsh; do
  source $zsh_source
done

autoload -U compinit
compinit

# This should be loaded after compinit
source <(kubectl completion zsh)
