# load zplug configuration
[[ -f $HOME/.zsh/zplug.zsh ]] && source $HOME/.zsh/zplug.zsh


# Load ubuntu related configurations

uname -v | grep -q "Ubuntu"
ubuntu=$?

if [ ${ubuntu} = 0 ]; then
  for zsh_source in $HOME/.zsh/configs/ubuntu/*.zsh; do
    source $zsh_source
  done
fi

# load custom configurations
for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

# load fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load osx related configurations

if [ "$(uname)" = 'Darwin' ]; then
  for zsh_source in $HOME/.zsh/configs/darwin/*.zsh; do
    source $zsh_source
  done
fi

[[ -f $HOME/.aliases ]] && source $HOME/.aliases

# load functions
for zsh_source in $HOME/.zsh/functions/*.zsh; do
  source $zsh_source
done

autoload -U compinit
compinit

