---
- name: 'Check win32yank exists'
  stat:
    path: '/usr/local/bin/win32yank-x64.exe'
  register: result
- name: 'Setup win32yank'
  block:
    - name: 'Download win32yank file'
      get_url:
        url: "https://github.com/equalsraf/win32yank/releases/download/v{{ win32yank_version }}/win32yank-x64.zip"
        dest: '/tmp/win32yank-x64.zip'
    - name: 'Unzip'
      unarchive:
        src: '/tmp/win32yank-x64.zip'
        dest: '/tmp'
    - name: 'mv win32yank.exe to /usr/local/bin'
      become: true
      copy:
        src: '/tmp/win32yank.exe'
        dest: '/usr/local/bin/win32yank.exe'
        owner: 'root'
        group: 'root'
        mode: '0755'
  when:
    - not result.stat.exists

