---
- name: 'Install copyq (Ubuntu)'
  become: true
  block:
    - name: 'Add repo'
      apt_repository:
        repo: 'ppa:hulk/copyq'
        state: 'present'
    - name: 'Install'
      apt:
        name: 'copyq'
        state: 'latest'
        update_cache: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
# m1 mac does not support copyq
# - name: 'Install copyq (osx)'
#   homebrew_cask:
#     name: 'copyq'
#     state: 'latest'
#   when:
#     - ansible_facts['os_family'] == 'Darwin'
