packages:
  common:
    - zsh
    - neovim
    - vim
    - curl
    - jq
    - direnv
    - tmux
    - git
    - tig
    - fzf
    - bat
    - ripgrep
  linux:
    - fd-find
    - xclip
    - pkg-config
    - openssl
    - libssl-dev
    # required by ruby-build
    - build-essential
    - autoconf
    - patch
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libgmp-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
    - uuid-dev
  osx:
    - fd
