live_config_reload = true

import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]

[window]

dimensions = { "columns" = 120, "lines" = 72 }
position = { "x" = 0, "y" = 0 }
opacity = 0.85

[scrolling]

history = 30000

[font]

normal = { "family" = "MesloLGS NF", "style" = "Regular" }
bold = { "family" = "MesloLGS NF", "style" = "Bold" }
italic = { "family" = "MesloLGS NF", "style" = "Italic" }

size = 12.0

[mouse]

hide_when_typing = true

[env]

TERM = "xterm-256color"
