live_config_reload = true

import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]

[window]

dimensions = { "columns" = 120, "lines" = 64 }
position = { "x" = 0, "y" = 0 }
opacity = 0.85

[scrolling]

history = 30000

[font]

normal = { "family" = "MesloLGS NF", "style" = "Regular" }
bold = { "family" = "MesloLGS NF", "style" = "Bold" }
italic = { "family" = "MesloLGS NF", "style" = "Italic" }

size = 12.0

[mouse]

hide_when_typing = true

[keyboard]

bindings = [
  # alt to command key like Mac
  { "key" = "V", "mods" = "Alt", "action" = "Paste" },
  { "key" = "C", "mods" = "Alt", "action" = "Copy" },

  { "key" = "+", "mods" = "Shift | Alt", "action" = "IncreaseFontSize" }, # + to increase font size
  { "key" = "=", "mods" = "Shift | Alt", "action" = "DecreaseFontSize" }, # - to decrease font size
  { "key" = "~", "mods" = "Shift | Alt", "action" = "ResetFontSize"},     # 0 to reset font size

  { "key" = "W", "mods" = "Alt", "action" = "Quit" },
  { "key" = "N", "mods" = "Alt", "action" = "SpawnNewInstance" },
  { "key" = "M", "mods" = "Shift | Alt", "action" = "ToggleMaximized" },

  { "key" = "F", "mods" = "Alt", "action" = "SearchForward" },
]

[env]

TERM = "xterm-256color"
