---
- name: 'Install ansible.posix'
  command: 'ansible-galaxy collection install ansible.posix'
- name: 'Increase max_user_watches'
  become: true
  ansible.posix.sysctl:
    name: 'fs.inotify.max_user_watches'
    value: '524288'
    sysctl_file: '/etc/sysctl.conf'
    reload: true
  when:
    # osx no longer have fs.inotify entity
    - ansible_facts['distribution'] == 'Ubuntu'
