---
- name: 'Install git (Ubuntu)'
  become: true
  apt:
    name: 'git'
    state: 'latest'
    update_cache: true
  tags:
    - 'update_deps'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install git (OSX)'
  homebrew:
    name: 'git'
    state: 'latest'
    update_homebrew: true
  tags:
    - 'update_deps'
  when:
    - ansible_facts['os_family'] == 'Darwin'
- name: 'Setup git credential helper (Ubuntu)'
  block:
    - name: 'Install libgnome-keyring-dev'
      become: true
      apt:
        name: 'libgnome-keyring-dev'
        state: 'latest'
        update_cache: true
    - name: 'Build gnome-keyring'
      become: true
      make:
        chdir: '/usr/share/doc/git/contrib/credential/gnome-keyring'
    - name: 'Make symlink'
      become: true
      file:
        src: '/usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring'
        dest: '/usr/lib/git-core/git-credential-gnome-keyring'
        owner: 'root'
        group: 'root'
        mode: '755'
        state: 'link'
  when:
   - ansible_facts['distribution'] == 'Ubuntu'
   - wsl_enabled == false
# Commented out since we use git for windows credential helper
# - name: Setup git credential helper (WSL)
#   when:
#    - ansible_facts['distribution'] == 'Ubuntu'
#    - wsl_enabled == true
- name: 'Install diff-so-fancy'
  become: true
  get_url:
    url: 'https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy'
    dest: '/usr/local/bin/diff-so-fancy'
    mode: '0755'
  tags:
    - 'update_deps'
- name: 'Install github cli (Ubuntu))'
  become: true
  apt:
    deb: https://github.com/cli/cli/releases/download/v0.9.0/gh_0.9.0_linux_amd64.deb
  tags:
    - 'update_deps'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install github cli (OSX)'
  homebrew:
    name: 'github/gh/gh'
    update_homebrew: true

