---
- name: "Use zsh as a login shell"
  become: true
  ansible.builtin.user:
    name: "bob"
    shell: "{{ '/opt/homebrew/bin/zsh' if ansible_facts['os_family'] == 'Darwin' else '/bin/zsh' }}"

- name: "Install starship"
  block:
    - name: Download Starship installer script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install_starship.sh
        mode: '0755'
    - name: Run Starship installer script
      ansible.builtin.shell: /tmp/install_starship.sh -y
      args:
        executable: /bin/bash
    - name: Clean up installer script
      ansible.builtin.file:
        path: /tmp/install_starship.sh
        state: absent
- name: "Install sheldon"
  ansible.builtin.shell: "~/.cargo/bin/cargo install sheldon"
