---
- name: 'Install google-musicmanager'
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-musicmanager-beta_current_amd64.deb
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
