---
- name: 'Add apt-repository'
  become: true
  apt_repository:
    repo: 'ppa:agornostal/ulauncher'
    state: 'present'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
- name: 'Install ulauncher'
  become: true
  apt:
    name: 'ulauncher'
    state: 'latest'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
  tags:
    - 'update_deps'
