
---
- name: 'Install bat (Ubuntu)'
  block:
    - name: 'Install'
      become: true
      apt:
        name: 'bat'
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
    - name: 'Create ~/.local/bin'
      file:
        path: "{{ home_dir }}/.local/bin"
        state: 'directory'
        mode: '0755'
    - name: 'Symlink batcat to bat'
      file:
        src: '/usr/bin/batcat'
        dest: "{{ home_dir }}/.local/bin/bat"
        state: 'link'
        force: true

- name: 'Install bat (osx)'
  homebrew:
    name: 'bat'
    update_homebrew: true
    state: 'latest'
  when:
    - ansible_facts['os_family'] == 'Darwin'
