---
- name: 'Install steam (Ubuntu)'
  become: true
  apt:
    deb: 'https://steamcdn-a.akamaihd.net/client/installer/steam.deb'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
- name: 'Install skype (Ubuntu)'
  become: true
  apt:
    deb: 'https://go.skype.com/skypeforlinux-64.deb'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false

