---
- name: Update package cache
  hosts: all
  roles:
    - update_package_cache
- name: Install essential packages
  hosts: all
  roles:
    - essential_packages
- name: Install custom packages
  hosts: all
  roles:
    - custom_packages
- name: Setup common environment
  hosts: all
  roles:
    - common_environment

