---
- name: Update package cache
  hosts: all
  roles:
    - update_package_cache
- name: Setup
  hosts: all
  roles:
    - essential_packages
- name: Setup Ubuntu-specific environment
  hosts: "wsl:ubuntu"
  become: yes
  roles:
    - ubuntu

- name: Setup macOS-specific environment
  hosts: osx
  become: no
  roles:
    - osx
