---
- name: Setup common environment
  hosts: all
  roles:
    - common
# - name: Setup Ubuntu-specific environment
#   hosts: "wsl:ubuntu"
#   become: yes
#   roles:
#     - ubuntu

# - name: Setup macOS-specific environment
#   hosts: osx
#   become: no
#   roles:
#     - osx
