# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH

# # Preferred editor for local and remote sessions
export EDITOR='vim'

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
export PATH=${JAVA_HOME}/bin:${PATH}

# nodejs
export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.nodebrew/current/bin/npm:$PATH

# pyenv
eval "$(pyenv init -)"

# brew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# direnv
eval "$(direnv hook zsh)"

# Homebrew
if [ -f ~/.brew_github_api_token ]; then
  source ~/.brew_github_api_token
fi

if [ -f ~/.github_api_token ]; then
  source ~/.github_api_token
fi

# go
export GOROOT=/usr/local/Cellar/go
export GOPATH="$HOME/.go"
export PATH="$GOPATH:$PATH"

source ~/.aws_config

# peco

function peco-select-history() {
  local tac
  if which tac > /dev/null; then
    tac="tac"
  else
    tac="tail -r"
  fi
  BUFFER=$(\history -n 1 | \
    eval $tac | \
    peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle clear-screen
 }
 zle -N peco-select-history
 bindkey '^r' peco-select-history

 HISTFILE=~/.zsh_history
 HISTSIZE=1000
 SAVEHIST=1000
