---
- name: "Check if cargo is installed"
  shell: command -v hoge
  register: cargo_exists
  ignore_errors: true
- name: "Download rustup"
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: true
  when: cargo_exists is failed
- name: "Install rust"
  ansible.builtin.shell: "/tmp/sh.rustup.rs -y"
  when: cargo_exists is failed
