---
- name: 'Install fd (Ubuntu)'
  become: true
  apt:
    deb: "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd_{{ fd_version }}_amd64.deb"
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install fd (osx)'
  homebrew:
    name: 'fd'
    update_homebrew: true
    state: 'latest'
  when:
    - ansible_facts['os_family'] == 'Darwin'

